---
- name: create uwsgi startup script
  template: src=uwsgi_start.sh.j2
            dest={{ project_virtualenv_dir }}/bin/uwsgi_start
            owner={{ nginx_user }}
            group={{ nginx_user }}
            mode=0755
            backup=yes

- include: selinux_nginx_socket_write.yaml

- name: create uwsgi log folder
  file: path={{ application_log_dir }}
        owner={{ nginx_user }}
        group={{ nginx_user }}
        mode=0744
        state=directory

- name: create nginx uwsgi site config
  template:
    src: flask_app.nginx.j2
    dest: '{{ nginx_sites_available_dir }}/{{ project_name }}'
  tags: flask.deploy
  notify: reload nginx

- name: enable nginx uwsgi site
  file:
    src: '{{ nginx_sites_available_dir }}/{{ project_name }}'
    dest: '{{ nginx_sites_enabled_dir }}/{{ project_name }}'
    state: link
  notify: reload nginx
