---
sudo: false
language: python
python:
  - 3.6
install:
  - cp backend/config.example.py backend/config.py
#  - pip install tox-travis
  - pip install travis-sphinx guzzle-sphinx-theme
script:
#  - tox
  - travis-sphinx build --source=docs
#services:
#  - redis-server
after_success:
  - travis-sphinx deploy
