---
galaxy_info:
  author: Simon Baerlocher <sbaerlocher@sbaerlocher.ch>
  description: "Redis installer"
  license: license (MIT)
  min_ansible_version: 2
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - trusty
    - name: Archlinux
      versions:
      - all
  categories:
    - database:nosql 

dependencies: []