---
galaxy_info:
  author: Sudheer Satyanarayana
  description: Ansible Role to install opendkim and setup DKIM for domains.
  company: Gavika Information Technologies Pvt. Ltd.
  license: BSD
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - security
    - email
dependencies: []
